### ISSUE TITLE
chromVAR parameters for differential TF motifs analysis

### ISSUE THREAD

**Issue by ghost** [buenrostrolab/dscATAC_analysis_code#1]
Hello,

I really appreciate your work and the paper you just published.

I was wondering if you could share the code you used for chromVAR when you analyse the difference between untreated and stimulated cells? 
Was chromVAR run only on the untreated cells to produce Fig 4-d and another time with all the cells to calculate the differential TF scores we can see in Fig 5-b? 

I'm trying to use chromVAR for a similar analysis and stumble upon these kind of questions. 
Thank you for your help!

**Comment by caleblareau** [comment]
Hi,

Thanks for the kind words. This analysis was split between a couple of us, so I'm working on gathering up the code. But to answer your question, we computed one set of background peaks for all the data and then ran chromvar always using that same set of background peaks. In other words, they were run altogether. If you run them separately, you would lose TFs associated with global gain of accessibility in a stimulation because of the differences in background peaks.

**Comment by ghost** [comment]
Hi, 
Thank you for your answer, it's really helpful.

**Comment by caleblareau** [comment]
@PachAP-1 thanks! glad this was helpful. 

Hopefully the chromVAR logic makes sense now. This was the (matlab) script used to perfom the differential analysis of the TFs produced -- https://github.com/buenrostrolab/dscATAC_analysis_code/blob/master/bonemarrow/m99_diff_TFs_share.m

I know that you said that you are working on a similar analysis, so I hope that this enables you to reproduce the analytical technique.
